version: "3.9"

services:
  mysql:
    image: mysql:8.3
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_vani_heroes
      MYSQL_USER: vani_heroes
      MYSQL_PASSWORD: vani_heroes
    volumes:
      - ./data/mysql:/var/lib/mysql
